# syntax=docker/dockerfile:1
ARG NODE_VERSION=22.1

FROM node:${NODE_VERSION}-alpine
RUN apk update && apk upgrade --no-cache openssl
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Run the application.
CMD ["node", "./dist/index.js"]

# Expose the port that the application listens on.
EXPOSE 8080