# syntax=docker/dockerfile:1
ARG NODE_VERSION=20.10.0

FROM --platform=linux/amd64 node:${NODE_VERSION}-alpine
WORKDIR /app

# Copy the rest of the source files into the image.
COPY . .
RUN npm install
RUN npm run build

# Run the application.
CMD ["node", "./dist/index.js"]

# Expose the port that the application listens on.
EXPOSE 8080