export const TAX_EXPORT_CONFIG = {
  CURRENCY_SYMBOL: 'MINA',
  NANOMINA_PER_MINA: 1_000_000_000,
  MAX_EXPORT_DAYS: 3650, // 10 years
  ADDRESS_LENGTH: 55,
  MINA_TOKEN_ID: 1,
  MAX_ACCOUNTS_PER_REQUEST: 10,
  DEFAULT_PAYOUT_KEYWORDS: ['Payout'],
} as const;
