# .github/workflows/pr-check.yml
name: PR Check

on:
  pull_request:
    branches: [ main ]
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

    - name: Run build
      run: npm run build